#!/bin/bash

sudo useradd -m $1
sudo echo $1:$2 | sudo chpasswd
sudo mv authorized_keys /home/$1/.ssh/


# Créez le dossier pour le site
sudo mkdir /home/$1/
sudo chown -R $1:www-data home/$1
sudo chmod -R 755 /home/$1

# Créez le fichier de configuration Nginx
sudo cat << EOF > /etc/nginx/sites-available/$1
server {
        listen 80;
        listen [::]:80;

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /home/$1/;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name $1-site;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
            
                try_files $uri $uri/ =404;
        }

        # pass PHP scripts to FastCGI server
        #
        location ~ \.php$ {
              include snippets/fastcgi-php.conf;
        
              # With php-fpm (or other unix sockets):
              fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
              # With php-cgi (or other tcp sockets):
              # fastcgi_pass 127.0.0.1:9000;
        }

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
    }
EOF

sudo ln -s /etc/nginx/sites-available/$1 /etc/nginx/sites-enabled/

# Redémarrez Nginx
sudo service nginx restart

